ProductCard
js-tasks-ru/jsbasic-20221215_lana-lisa pull request #12
Opened 2023-01-28 21:20 UTC by Svetlana-Li

Подскажите пожалуйста, на сколько корректно вставлять создание элемента (карточки товара) в метод addEventListeners(), а затем вызывать этот метод в конструкторе?

2023-01-28 21:21 UTC, jsru commented
Добавляю преподавателя (@koalex) для код-ревью.

2023-01-29 16:46 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-01-29 16:47 UTC, Svetlana-Li commented
Добрый день! Не получается сделать так? чтобы при клике на Добавить товар, добавлялся нудный id, везде добавляется один и тот же товар

2023-01-30 04:46 UTC, koalex commented
Ответил в дискорде

вс, 29 янв. 2023 г. в 23:47, Svetlana-Li ***@***.***>:

> Добрый день! Не получается сделать так? чтобы при клике на Добавить товар,
> добавлялся нудный id, везде добавляется один и тот же товар
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/js-tasks-ru/jsbasic-20221215_lana-lisa/pull/12#issuecomment-1407713235>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACBEESB2YX4ILCMIML3OPPDWU2NJDANCNFSM6AAAAAAUJ3EEWI>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-01-30 05:06 UTC, koalex requested changes
Ответил в дискорде

2023-01-30 15:00 UTC, jsru commented
Добавляю преподавателя (@koalex) для код-ревью.

2023-01-30 17:34 UTC, koalex approved these changes

2023-01-30 17:35 UTC, merged